"""Pydantic schemas for chart endpoints."""

import json
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator


# --- Requests ---


class ChartGenerateRequest(BaseModel):
    """Request to generate a chart from a natural language prompt."""

    prompt: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="Chart description in natural language",
    )
    table_filter: Optional[list[str]] = Field(
        None,
        description='Filter tables, e.g. ["crm_deals", "crm_contacts"]. '
        "Related reference tables (statuses, categories, enum values) will be automatically included.",
    )


class ChartSaveRequest(BaseModel):
    """Request to save a generated chart."""

    title: str = Field(..., max_length=255)
    description: Optional[str] = None
    user_prompt: str
    chart_type: str = Field(..., pattern=r"^(bar|line|pie|area|scatter|indicator|table|funnel|horizontal_bar)$")
    chart_config: dict[str, Any]
    sql_query: str


class ChartConfigUpdateRequest(BaseModel):
    """Request to partially update chart_config (deep merge)."""

    config: dict[str, Any] = Field(
        ..., description="Partial chart_config to merge with existing"
    )


# --- Chart spec (from AI) ---


class ChartSpec(BaseModel):
    """Chart specification generated by AI."""

    title: str
    chart_type: str = Field(..., description="bar | line | pie | area | scatter | indicator | table | funnel | horizontal_bar")
    sql_query: str
    data_keys: dict[str, Any] = Field(
        ..., description='{x: "stage", y: "count"} or {x: "month", y: ["revenue", "cost"]}'
    )
    colors: Optional[list[str]] = None
    description: Optional[str] = None


# --- Responses ---


class ChartGenerateResponse(BaseModel):
    """Response for chart generation."""

    chart: ChartSpec
    data: list[dict[str, Any]]
    row_count: int
    execution_time_ms: float


class ChartResponse(BaseModel):
    """Saved chart response."""

    id: int
    title: str
    description: Optional[str] = None
    user_prompt: str
    chart_type: str
    chart_config: dict[str, Any]
    sql_query: str
    is_pinned: bool
    created_at: datetime
    updated_at: datetime

    @field_validator("chart_config", mode="before")
    @classmethod
    def parse_chart_config(cls, v: Any) -> dict[str, Any]:
        if isinstance(v, str):
            return json.loads(v)
        return v


class ChartListResponse(BaseModel):
    """Paginated list of saved charts."""

    charts: list[ChartResponse]
    total: int
    page: int
    per_page: int


class ChartDataResponse(BaseModel):
    """Updated chart data (re-executed SQL)."""

    data: list[dict[str, Any]]
    row_count: int
    execution_time_ms: float


class ChartPromptTemplateResponse(BaseModel):
    """Chart prompt template response."""

    id: int
    name: str
    content: str
    is_active: bool
    created_at: datetime
    updated_at: datetime


class ChartPromptTemplateUpdateRequest(BaseModel):
    """Request to update chart prompt template."""

    content: str = Field(..., min_length=10, description="Prompt template content")
